name: Publish Updates
on:
  push:
    branches: 
      - 'main'
    paths:
      - 'dependency.lic'
      - 'noop.lic'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['4.0']
    name: Publish Updates
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: '20'
      - uses: ruby/setup-ruby@708024e6c902387ab41de36e1669e43b5ee7085e # v1.283.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Release updates to Tillmen's Lich repository
        env:
          AUTHOR: ${{ secrets.repo_author }}
          PASSWORD: ${{ secrets.repo_password }}
          TRAVIS_COMMIT: ${{ github.sha }}
          TRAVIS_COMMIT_RANGE: ${{ github.event.before }}..${{ github.sha }}
        run: bin/repo
