name: RSpec Tests
on:
  push:
    branches: 
      - 'master'
    paths:
      - "*.lic"
      - "*.rb"
  pull_request:
    paths:
      - "*.lic"
      - "*.rb"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_WITHOUT: 'gtk:vscode:profanity'
    strategy:
      matrix:
        ruby: ['4.0']
    name: Run tests on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ruby/setup-ruby@708024e6c902387ab41de36e1669e43b5ee7085e # v1.283.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run RSpec tests
        run: bundle exec rspec
